variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_IMAGE: countryguesser-backend

stages:
  - build
  - test
  - sonarqube
  - dockerize
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

sonarqube:
  stage: sonarqube
  script:
    - ./gradlew test jacocoTestReport sonarqube

dockerize:
  stage: dockerize
  script:
    - ./gradlew clean assemble
    - docker build -t $DOCKER_IMAGE .
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker start countryguesser_db
    - docker stop countryguesser_backend_staging
    - docker rm countryguesser_backend_staging
    - docker run -d -p 8090:8080 --net=docker_countryguesser --env spring_profiles_active=staging --name=countryguesser_backend_staging countryguesser-backend
  only:
    - main